# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f811d2f509eef21573bf54f689afa17f94540bfd5c79a04d2abf58eaf864e138aaa86b0380325a8ebaf33db7a57ff331fd3ef7d8c83b7547ec1db7cd6b455157

test:
  secret_key_base: f4a99f8bb9f6bd4ec8de9393f0570db3e95631c3978a926399f37ecb9bc7c77b3a3efa30dfc47cf1ae9f68dc825f40de94f58704a97a6cbbfc7d72c1bcdaf812

# Make sure this key is different than the production and ideally set it as an environment as well.
demo:
  secret_key_base: u8asdkt2l19f6bd4ec8de9393f0570db3easdf2kl902kasdf29f37ecb9bc7c77b3a3efa30dfc47cf1ae9f68dc825f4de94f58704a97asdf090aj92asdf2io87s

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
